# Generated by Django 5.1.7 on 2025-03-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0002_cinema_screening_cinema_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Cinema',
        ),
        migrations.DeleteModel(
            name='Screening',
        ),
    ]
